### ISSUE TITLE
Bigsur

### ISSUE THREAD

**Issue by juninhoall** [jbagaresgaray/AMD-Ryzentosh---Ryzen-7-3700x-Gigabyte-B550M-Auros-Pro-RX-5500XT#1]
I've tryed make a ryzentosh using step by step of opencore, but only the boot working in pen-drive, never using ssd/clover.

Not Started using Clover in SSD

**Comment by jbagaresgaray** [comment]
@juninhoall try to use https://github.com/corpnewt/gibMacOS in creating the bootable USB for BigSur then use the Open Core Mac Recovery in downloading the recovery image for Big Sur... and use the mac recovery option since that's the safest and guaranteed way on proceeding and completing the installation..

**Comment by juninhoall** [comment]
Thanks so much, I'll try to install.

**Comment by jbagaresgaray** [comment]
You're welcome.. please get back if you encounter some issues with your installation.

**Comment by juninhoall** [comment]
Hi, I'm using the Catalina, it's clean work with XCODE.... Thanks so much

**Comment by jbagaresgaray** [comment]
@juninhoall ... Cool... Good to hear... You're welcome...
